In [6]:
import pandas as pd

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [1]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     --- ------------------------------------ 1.0/11.9 MB 3.4 MB/s eta 0:00:04
     ----- ---------------------------------- 1.6/11.9 MB 3.3 MB/s eta 0:00:04
     -------- ------------------------------- 2.6/11.9 MB 3.7 MB/s eta 0:00:03
     ------------ --------------------------- 3.7/11.9 MB 4.0 MB/s eta 0:00:03
     --------------- ------------------------ 4.5/11.9 MB 4.0 MB/s eta 0:00:02
     ----------------- ---------------------- 5.2/11.9 MB 4.0 MB/s eta 0:00:02
     --------------------- ------------------ 6.3/11.9 MB 4.1 MB/s eta 0:00:02
     ----------------------- ---------------- 7.1/11.9 MB 4.1 MB/s eta 0:00:02
     --------------------------- ------------ 8.1/11.9 MB 4.1 MB/s eta 0:00:01
     ------------------------------ --------- 8.9/11.9 MB 4.1 MB/s eta 0:00:01
     -------------------------------- ------- 9.7/11.9 MB 4.1 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 4.1 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 4.1 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 4.1 MB/s  0:00:03
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=a040286089bef766b1a9a3c2ef5c01b213583bc009328ae1b82d1ddcbff644d6
  Stored in directory: c:\users\auser\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [2]:
import mysql.connector

In [4]:
conn = mysql.connector.connect(host='localhost' , user='root' , password='' , database='world')

In [8]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND' " , conn)

C:\Users\AUSER\AppData\Local\Temp\ipykernel_10296\1766388275.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'IND' " , conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]