In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("placement.csv")

In [6]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [8]:
import requests
from io import StringIO

In [11]:
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 18.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests. get(url, headers=headers)
data = StringIO(req. text)
pd. read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [15]:
# SEP PARAMETER : if the columns of the csv files are mixed and not names then sep + \t + naming the columns can help out

In [16]:
# HEADER Parameter : pd.read_csv("placement.csv" , header = 1) -- make the firsr row the header

In [18]:
# usecols
pd.read_csv("placement.csv" , usecols=['cgpa' , 'iq'])

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

In [19]:
#skiprows : pd.read_csv("placement.csv" , skiprows=[0,1]) -- skip any row

In [20]:
#nrows : pd.read_csv("placement.csv" , nrows=100) -- only specific 100 rows

In [21]:
#encoding : pd.read_csv("placement.csv" , encoding = 'latin - 1')  -- encoding error

In [22]:
#suppose there are rows which have extra values for eg a dataset has 5 columns and suddenly one row has six then :
#pd.read_csv("placement.csv" , error_bad_lines = False)

In [23]:
#want to convert float value to integer 
#pd.read_csv("placement.csv" , dtype = {'target' : int})

In [24]:
#Handling dates
#pd.read_csv("placement.csv" , parse_dates = ['dates'])

In [25]:
#Handling huge dataset in chunks
#pd.read_csv("placement.csv" , chunksize = 5000)